name: Deploy Site

on:
  push:
    branches: [dev]
    paths:
      - 'docs/**/*.md'
      - 'packages/**/*.md'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build Site
        run: npx --no-install vant-cli build-site

      - name: Deploy for GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: site-dist
          token: ${{ secrets.VANT_UI_TOKEN }}
          repository-name: vant-ui/vant-ui.github.io
          target-folder: vant-weapp
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true
          clean-exclude: |
            0.x
